### ISSUE TITLE
Addon has completely stopped working - does nothing.

### ISSUE THREAD

**Issue by etsnyman** [dessant/youtube-video-quality#15]
**System**
* OS name: Ubuntu Linux
* OS version: 21.04
* Browser name: Firefox
* Browser version: 89.0.1
* Extension version: 1.0.0

**Bug description**
The addon does absolutely nothing. Every single Youtube link I open, no matter how I open it or how I set up the addon, defaults to "Auto" and a video resolution I did not choose. Addon simply has absolutely no affect at all on Youtube videos' quality.

I don't know what else to say...

**Comment by t0stiman** [comment]
Same here on Windows 10

**Comment by kiwi5** [comment]
Same here, except it forces the highest quality setting, even changing it to highest just after I manually pick the lower one, multiple times - it just won't let the lower one stay after I pick it on video. This is especially noticable & troublesome on videos that are in 4k.
It happened to me on firefox on both win10 and linux, and only disabling the addon would let me pick what I want.

Youtube must have changed something recently and the addon needs to be updated to accomodate for it.

**Comment by etsnyman** [comment]
I assumed something similar, kiwi5.

I hope dessant can do something about it.... I'm no dev/coder i'm afraid.

**Comment by dessant** [comment]
This issue has been fixed in version 2.0.0, the new release will be available on extension stores in the next few days.
