### ISSUE TITLE
Does nothing in Chrome v100.0.4896.60

### ISSUE THREAD

**Issue by JustNilt** [dessant/youtube-video-quality#16]
**System**

* OS name: Windows 10 Pro
* OS version: 10 Pro
* Browser name: Chrome
* Browser version: 100.0.4896.60
* Extension version: 1.0.0

**Bug description**

Installed from Chrome Web Store.  Checked settings for 1080p.  Loaded YouTube but all videos still default to Auto and reduce quality after a few seconds.  The extension appears to be completely ineffective.

**Logs**

No errors for extension, it simply doesn't work.

**Comment by dessant** [comment]
This issue has been fixed in version 2.0.0, the new release will be available on extension stores in the next few days.
