### ISSUE TITLE
Wrong quality level

### ISSUE THREAD

**Issue by Dominiquini** [dessant/youtube-video-quality#19]
**System**

* OS name: Windows
* OS version: 21H2
* Browser name: Firefox
* Browser version: 105.0.3
* Extension version: 1.0.0

**Bug description**
I configure the extension to set YouTube to 1080p, but the player always defaults to 4k. When I try to change the quality on the player, it soon changes to 4k!

**Comment by aderchox** [comment]
I have the same issue, it seems that when the chosen quality doesn't exist, it puts it on the highest quality! I've set it on 480p, but it sets it on 1080p and doesn't allow changing it either.

**Comment by dessant** [comment]
@Dominiquini, version 2.0.0 was just released and it should fix your issue, the new release will become available on extension stores in the next few days.
