### ISSUE TITLE
Video resolutions are applied to all youtube tabs open

### ISSUE THREAD

**Issue by rc6ty** [dessant/youtube-video-quality#23]
**System**

* OS name: Windows 10 Pro 21H2
* OS version: 19044.2965
* Browser name: Firefox
* Browser version: 113.0.1
* Extension version: 2.0.0

**Bug description**
Video resolutions are applied to all youtube tabs open and you can't change it independently for each video that's open.
For example when you want a music video in the background to play at 360p and a product review to play at 1440p you cannot do that, both are forced to play at the same resoltion.

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
We should add an option that disables syncing resolution changes, let's track this issue at https://github.com/dessant/youtube-video-quality/issues/24.
