### ISSUE TITLE
The extension settings always reset to 1080p

### ISSUE THREAD

**Issue by Quezako** [dessant/youtube-video-quality#3]
The extension settings always reset to 1080p, so it:s useless for my needs, which are to force down 720p.
Extension v0.2.0
Browser: Cent 4.0.9, based on Chrome 74.

**Comment by dessant** [comment]
Thanks for reporting the issue. As you know YouTube constantly changes, so extensions which interface with it are expected to break at some point and need to be updated. I've seen you've also rated down the extension on the Chrome Web Store and reported the issue there.

Please don't report issues in reviews, and don't rate down extensions that stop working when developers are offering you a way to signal problems. It's best to just open an issue and wait, rating down extensions for such issues is offputting and unfair, and it doesn't motivate anyone to work in their free time to release updates.

**Comment by dessant** [comment]
This issue wasn't reproducible on my part, but may be fixed by version 1.0.0.
