### ISSUE TITLE
Skipping by using the keyboard right-arrow key causes video to pause.

### ISSUE THREAD

**Issue by Snake883** [dessant/youtube-video-quality#5]
**System**
* OS name: [e.g. Windows, Ubuntu]
Windows

* OS version: [e.g. 10]
7

* Browser name: [e.g. Chrome, Firefox]
Firefox

* Browser version: [e.g. 60]
72.0.2

* Extension version: [e.g. 1.0.0]
1.0.0

**Bug description**
Skipping by using the keyboard right-arrow key causes video to pause.  Then I have to press the Play button to continue the video.

**Logs**
None

**Comment by dessant** [comment]
I haven't been able to reproduce this issue with Firefox on Linux, the video buffers a bit on right-arrow press and the playback resumes. I'll try to test it on Windows.

**Comment by dessant** [comment]
@snakyjake1, are you using any other extensions that could interfere? Please disable other extensions and reload the page to test.

**Comment by Snake883** [comment]
Thank you for the kind response.  You are correct, another add-on was causing the problem.  I have a YouTube buffer disabling addon.
