### ISSUE TITLE
Set video quality for embedded videos

### ISSUE THREAD

**Issue by madvik** [dessant/youtube-video-quality#6]
When I naviagte and find a article with a video (youtube). I play it but the quality is not modify.

It is posssible to detect it and aplly with embed video ?

**Comment by dessant** [comment]
The API used to set the video quality is no longer available for embedded videos, Google has deprecated it. I'll look into restricting the available resolutions and see if that works.

**Comment by dessant** [comment]
It seems this issue has solved itself, YouTube now provides the necessary APIs for embedded videos too, and the default video quality is set as expected.
