### ISSUE TITLE
Can you include facebook videos?

### ISSUE THREAD

**Issue by cg00001** [dessant/youtube-video-quality#8]
Or make another extension that handles facebook videos?
I have a slow laptop and every time I want to see a video I have to manually set it to 360p -facebook's SD only setting rarely works.

**Comment by dessant** [comment]
This extension is only for configuring the quality of YouTube videos, but you may be able to solve your issue by setting the default video quality to `SD only` if you have a Facebook account.

This article is a bit dated, but a similar setting should be available: https://www.ghacks.net/2015/07/22/how-to-set-a-default-quality-for-facebook-videos/
